import dotenv 
import os
dotenv.load_dotenv()
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "YOUR_TELEGRAM_BOT_TOKEN")
DATABASE_URL = os.getenv("DATABASE_URL", "YOUR_DATABASE_URL")
BOT_USERNAME = os.getenv("BOT_USERNAME", "YOUR_BOT_USERNAME")
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES", "30"))
SECRET_KEY=os.getenv("SECRET_KEY", "YOUR_SECRET_KEY")
ALGORITHM=os.getenv("ALGORITHM", "YOUR_ALGORITHM")
API_BASE_URL = os.getenv("API_BASE_URL", "YOUR_API_BASE_URL")